### ISSUE TITLE
Dynamic LinearLayout (WTF, Carl???)

### ISSUE THREAD

**Issue by djarktic** [vladislav805/GUAPSchedule#10]
Динамический лэйаут - это пиз*ец.
Надо использовать ListView, а в идеальном случае - RecyclerView

**Comment by vladislav805** [comment]
ListView, который будет несколько раз перезаписываться по время скролла?

**Comment by djarktic** [comment]
да

**Comment by vladislav805** [comment]
А RecyclerView что за фрукт?
